### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by CursedGamerZ** [vipintom/stealthFox#6]
I'll be honest i don't know why this happened on windows. Currently using mouse button 4 & 5 for now but would love to see a fix for this.

Window 11 Pro 10.0.22631 Build 22631.
https://github.com/vipintom/stealthFox/assets/6599748/2c5e1638-c4bb-4f2f-ad82-4a58d32d248c

**Comment by OTomHD** [comment]
Hello
I found I have the same issue on arch Linux with Firefox 122.0 I was able to fix this for myself by changing some of the values in the userChrome.css file

![1](https://github.com/vipintom/stealthFox/assets/36340981/80835025-1632-4efb-9da6-f38bfc444c09)


In the #nav-bar section I changed padding-left from 65px to 80px

![2](https://github.com/vipintom/stealthFox/assets/36340981/a74ec6ea-48fe-42c0-83c8-9cc8b36382af)


and the #TabsToolbar>.titlebar-buttonbox-container section I changed top from 14px to 9px

![3](https://github.com/vipintom/stealthFox/assets/36340981/9a508ae7-0cc3-4ebb-bd3c-6a07e987a567)


Also I found that these button will disappear if Firefox is unfocused so thanks to this reddit comment: 
https://www.reddit.com/r/FirefoxCSS/comments/1ajduf3/comment/kp1lo6d/?utm_source=share&utm_medium=web2x&context=3

Adding this section fixes that issue as well
```
:root[tabsintitlebar] #titlebar:-moz-window-inactive { opacity: 100 !important; }
```

Whole windows Control section if you want to just copy and replace
```
/* Moving Windows Control */

#nav-bar {
  margin-left: 0px !important;
  border-top: 0px !important;
  margin-top: 0px;
  padding-left: 80px !important;
}

#titlebar {
  appearance: none !important;
  height: 0px;
}


#TabsToolbar>.titlebar-buttonbox-container {
  display: block;
  position: absolute;
  top: 9px;
}

#TabsToolbar {
  background: #2B2A34 !important;
  background-color: #2B2A34 ! important;
  color: #2B2A34 !important;
}

/* Fix for dissapearing windows controls on unfocus */
:root[tabsintitlebar] #titlebar:-moz-window-inactive { opacity: 100 !important; }
```

I don't think this is the best way to fix this issue and you may need to change the values if it's not quite the same on your computer but hopefully this helps

**Comment by goldenfish99** [comment]
Would it be also possible to move the buttons to the right corner?

**Comment by CursedGamerZ** [comment]
@OTomHD , Ty so much i had to increase left padding to 130px but the fix is working great.
